//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVM_Webservice_Client.SVMWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.svm", ConfigurationName="SVMWebservice.ExportContestServicePortType")]
    public interface ExportContestServicePortType {
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="urn:sayHelloWorldFrom", ReplyAction="urn:sayHelloWorldFromResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromResponse sayHelloWorldFrom(SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sayHelloWorldFrom", ReplyAction="urn:sayHelloWorldFromResponse")]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromResponse> sayHelloWorldFromAsync(SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest request);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfContestsByDate", ReplyAction="urn:getListOfContestsByDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateResponse getListOfContestsByDate(SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfContestsByDate", ReplyAction="urn:getListOfContestsByDateResponse")]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateResponse> getListOfContestsByDateAsync(SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest request);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfMatches", ReplyAction="urn:getListOfMatchesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SVM_Webservice_Client.SVMWebservice.getListOfMatchesResponse getListOfMatches(SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfMatches", ReplyAction="urn:getListOfMatchesResponse")]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfMatchesResponse> getListOfMatchesAsync(SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest request);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfContestsByTeam", ReplyAction="urn:getListOfContestsByTeamResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamResponse getListOfContestsByTeam(SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfContestsByTeam", ReplyAction="urn:getListOfContestsByTeamResponse")]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamResponse> getListOfContestsByTeamAsync(SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest request);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfTeams", ReplyAction="urn:getListOfTeamsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SVM_Webservice_Client.SVMWebservice.getListOfTeamsResponse getListOfTeams(SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getListOfTeams", ReplyAction="urn:getListOfTeamsResponse")]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfTeamsResponse> getListOfTeamsAsync(SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloWorldFrom", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class sayHelloWorldFromRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string from;
        
        public sayHelloWorldFromRequest() {
        }
        
        public sayHelloWorldFromRequest(string from) {
            this.from = from;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloWorldFromResponse", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class sayHelloWorldFromResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public sayHelloWorldFromResponse() {
        }
        
        public sayHelloWorldFromResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class ContestDTO : DTO {
        
        private ContactDetailsDTO contactDetailsField;
        
        private System.Nullable<System.DateTime> endField;
        
        private bool endFieldSpecified;
        
        private float feeField;
        
        private bool feeFieldSpecified;
        
        private bool finishedField;
        
        private bool finishedFieldSpecified;
        
        private string nameField;
        
        private SportDTO sportField;
        
        private System.Nullable<System.DateTime> startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ContactDetailsDTO contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
                this.RaisePropertyChanged("contactDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endSpecified {
            get {
                return this.endFieldSpecified;
            }
            set {
                this.endFieldSpecified = value;
                this.RaisePropertyChanged("endSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
                this.RaisePropertyChanged("feeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool finished {
            get {
                return this.finishedField;
            }
            set {
                this.finishedField = value;
                this.RaisePropertyChanged("finished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finishedSpecified {
            get {
                return this.finishedFieldSpecified;
            }
            set {
                this.finishedFieldSpecified = value;
                this.RaisePropertyChanged("finishedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public SportDTO sport {
            get {
                return this.sportField;
            }
            set {
                this.sportField = value;
                this.RaisePropertyChanged("sport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class ContactDetailsDTO : DTO {
        
        private string coordLatField;
        
        private string coordLongField;
        
        private string email1Field;
        
        private string email2Field;
        
        private string faxField;
        
        private LocationDTO locationField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string streetField;
        
        private string streetNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string coordLat {
            get {
                return this.coordLatField;
            }
            set {
                this.coordLatField = value;
                this.RaisePropertyChanged("coordLat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string coordLong {
            get {
                return this.coordLongField;
            }
            set {
                this.coordLongField = value;
                this.RaisePropertyChanged("coordLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
                this.RaisePropertyChanged("email1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
                this.RaisePropertyChanged("email2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public LocationDTO location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
                this.RaisePropertyChanged("phone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
                this.RaisePropertyChanged("phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("streetNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class LocationDTO : DTO {
        
        private string communityField;
        
        private string countryCodeField;
        
        private string districtField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string placeNameField;
        
        private string postalCodeField;
        
        private string provinceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string community {
            get {
                return this.communityField;
            }
            set {
                this.communityField = value;
                this.RaisePropertyChanged("community");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string placeName {
            get {
                return this.placeNameField;
            }
            set {
                this.placeNameField = value;
                this.RaisePropertyChanged("placeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContestDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MatchTypeDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactDetailsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartmentDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SportDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MemberDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TeamDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MatchDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class DTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uIDField;
        
        private bool uIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UIDSpecified {
            get {
                return this.uIDFieldSpecified;
            }
            set {
                this.uIDFieldSpecified = value;
                this.RaisePropertyChanged("UIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class MatchTypeDTO : DTO {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class DepartmentDTO : DTO {
        
        private string aliasField;
        
        private ContactDetailsDTO contactDetailsField;
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ContactDetailsDTO contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
                this.RaisePropertyChanged("contactDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class SportDTO : DTO {
        
        private DepartmentDTO departmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public DepartmentDTO department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class MemberDTO : DTO {
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string coordLatField;
        
        private string coordLongField;
        
        private string email1Field;
        
        private string email2Field;
        
        private System.Nullable<System.DateTime> entryDateField;
        
        private bool entryDateFieldSpecified;
        
        private string faxField;
        
        private string firstNameField;
        
        private string genderField;
        
        private bool hasPaidFeeField;
        
        private bool hasPaidFeeFieldSpecified;
        
        private string lastNameField;
        
        private LocationDTO locationField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string socialNumberField;
        
        private SportDTO sportField;
        
        private string streetField;
        
        private string streetNumberField;
        
        private string titleField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
                this.RaisePropertyChanged("birthDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string coordLat {
            get {
                return this.coordLatField;
            }
            set {
                this.coordLatField = value;
                this.RaisePropertyChanged("coordLat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string coordLong {
            get {
                return this.coordLongField;
            }
            set {
                this.coordLongField = value;
                this.RaisePropertyChanged("coordLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
                this.RaisePropertyChanged("email1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
                this.RaisePropertyChanged("email2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> entryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
                this.RaisePropertyChanged("entryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entryDateSpecified {
            get {
                return this.entryDateFieldSpecified;
            }
            set {
                this.entryDateFieldSpecified = value;
                this.RaisePropertyChanged("entryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool hasPaidFee {
            get {
                return this.hasPaidFeeField;
            }
            set {
                this.hasPaidFeeField = value;
                this.RaisePropertyChanged("hasPaidFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasPaidFeeSpecified {
            get {
                return this.hasPaidFeeFieldSpecified;
            }
            set {
                this.hasPaidFeeFieldSpecified = value;
                this.RaisePropertyChanged("hasPaidFeeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public LocationDTO location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
                this.RaisePropertyChanged("phone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
                this.RaisePropertyChanged("phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string socialNumber {
            get {
                return this.socialNumberField;
            }
            set {
                this.socialNumberField = value;
                this.RaisePropertyChanged("socialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public SportDTO sport {
            get {
                return this.sportField;
            }
            set {
                this.sportField = value;
                this.RaisePropertyChanged("sport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("streetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class TeamDTO : DTO {
        
        private MemberDTO contactPersonField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public MemberDTO contactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
                this.RaisePropertyChanged("contactPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.webservice.svm/xsd")]
    public partial class MatchDTO : DTO {
        
        private TeamDTO awayField;
        
        private bool cancelledField;
        
        private bool cancelledFieldSpecified;
        
        private ContactDetailsDTO contactDetailsField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> endField;
        
        private bool endFieldSpecified;
        
        private TeamDTO homeField;
        
        private MatchTypeDTO matchTypeField;
        
        private string nameField;
        
        private string remarksField;
        
        private System.Nullable<int> resultAwayField;
        
        private bool resultAwayFieldSpecified;
        
        private System.Nullable<int> resultHomeField;
        
        private bool resultHomeFieldSpecified;
        
        private System.Nullable<System.DateTime> startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public TeamDTO away {
            get {
                return this.awayField;
            }
            set {
                this.awayField = value;
                this.RaisePropertyChanged("away");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
                this.RaisePropertyChanged("cancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cancelledSpecified {
            get {
                return this.cancelledFieldSpecified;
            }
            set {
                this.cancelledFieldSpecified = value;
                this.RaisePropertyChanged("cancelledSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public ContactDetailsDTO contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
                this.RaisePropertyChanged("contactDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endSpecified {
            get {
                return this.endFieldSpecified;
            }
            set {
                this.endFieldSpecified = value;
                this.RaisePropertyChanged("endSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public TeamDTO home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("home");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public MatchTypeDTO matchType {
            get {
                return this.matchTypeField;
            }
            set {
                this.matchTypeField = value;
                this.RaisePropertyChanged("matchType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> resultAway {
            get {
                return this.resultAwayField;
            }
            set {
                this.resultAwayField = value;
                this.RaisePropertyChanged("resultAway");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultAwaySpecified {
            get {
                return this.resultAwayFieldSpecified;
            }
            set {
                this.resultAwayFieldSpecified = value;
                this.RaisePropertyChanged("resultAwaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> resultHome {
            get {
                return this.resultHomeField;
            }
            set {
                this.resultHomeField = value;
                this.RaisePropertyChanged("resultHome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultHomeSpecified {
            get {
                return this.resultHomeFieldSpecified;
            }
            set {
                this.resultHomeFieldSpecified = value;
                this.RaisePropertyChanged("resultHomeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfContestsByDate", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfContestsByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> date;
        
        public getListOfContestsByDateRequest() {
        }
        
        public getListOfContestsByDateRequest(System.Nullable<System.DateTime> date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfContestsByDateResponse", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfContestsByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public SVM_Webservice_Client.SVMWebservice.ContestDTO[] @return;
        
        public getListOfContestsByDateResponse() {
        }
        
        public getListOfContestsByDateResponse(SVM_Webservice_Client.SVMWebservice.ContestDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfMatches", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfMatchesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        public int contest;
        
        public getListOfMatchesRequest() {
        }
        
        public getListOfMatchesRequest(int contest) {
            this.contest = contest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfMatchesResponse", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfMatchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public SVM_Webservice_Client.SVMWebservice.MatchDTO[] @return;
        
        public getListOfMatchesResponse() {
        }
        
        public getListOfMatchesResponse(SVM_Webservice_Client.SVMWebservice.MatchDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfContestsByTeam", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfContestsByTeamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        public int team;
        
        public getListOfContestsByTeamRequest() {
        }
        
        public getListOfContestsByTeamRequest(int team) {
            this.team = team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfContestsByTeamResponse", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfContestsByTeamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public SVM_Webservice_Client.SVMWebservice.ContestDTO[] @return;
        
        public getListOfContestsByTeamResponse() {
        }
        
        public getListOfContestsByTeamResponse(SVM_Webservice_Client.SVMWebservice.ContestDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfTeams", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfTeamsRequest {
        
        public getListOfTeamsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfTeamsResponse", WrapperNamespace="http://webservice.svm", IsWrapped=true)]
    public partial class getListOfTeamsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.svm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public SVM_Webservice_Client.SVMWebservice.TeamDTO[] @return;
        
        public getListOfTeamsResponse() {
        }
        
        public getListOfTeamsResponse(SVM_Webservice_Client.SVMWebservice.TeamDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExportContestServicePortTypeChannel : SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportContestServicePortTypeClient : System.ServiceModel.ClientBase<SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType>, SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType {
        
        public ExportContestServicePortTypeClient() {
        }
        
        public ExportContestServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportContestServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportContestServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportContestServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromResponse SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.sayHelloWorldFrom(SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest request) {
            return base.Channel.sayHelloWorldFrom(request);
        }
        
        public string sayHelloWorldFrom(string from) {
            SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest inValue = new SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest();
            inValue.from = from;
            SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromResponse retVal = ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).sayHelloWorldFrom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromResponse> SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.sayHelloWorldFromAsync(SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest request) {
            return base.Channel.sayHelloWorldFromAsync(request);
        }
        
        public System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromResponse> sayHelloWorldFromAsync(string from) {
            SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest inValue = new SVM_Webservice_Client.SVMWebservice.sayHelloWorldFromRequest();
            inValue.from = from;
            return ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).sayHelloWorldFromAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateResponse SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfContestsByDate(SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest request) {
            return base.Channel.getListOfContestsByDate(request);
        }
        
        public SVM_Webservice_Client.SVMWebservice.ContestDTO[] getListOfContestsByDate(System.Nullable<System.DateTime> date) {
            SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest();
            inValue.date = date;
            SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateResponse retVal = ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfContestsByDate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateResponse> SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfContestsByDateAsync(SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest request) {
            return base.Channel.getListOfContestsByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateResponse> getListOfContestsByDateAsync(System.Nullable<System.DateTime> date) {
            SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfContestsByDateRequest();
            inValue.date = date;
            return ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfContestsByDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SVM_Webservice_Client.SVMWebservice.getListOfMatchesResponse SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfMatches(SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest request) {
            return base.Channel.getListOfMatches(request);
        }
        
        public SVM_Webservice_Client.SVMWebservice.MatchDTO[] getListOfMatches(int contest) {
            SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest();
            inValue.contest = contest;
            SVM_Webservice_Client.SVMWebservice.getListOfMatchesResponse retVal = ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfMatches(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfMatchesResponse> SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfMatchesAsync(SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest request) {
            return base.Channel.getListOfMatchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfMatchesResponse> getListOfMatchesAsync(int contest) {
            SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfMatchesRequest();
            inValue.contest = contest;
            return ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfMatchesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamResponse SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfContestsByTeam(SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest request) {
            return base.Channel.getListOfContestsByTeam(request);
        }
        
        public SVM_Webservice_Client.SVMWebservice.ContestDTO[] getListOfContestsByTeam(int team) {
            SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest();
            inValue.team = team;
            SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamResponse retVal = ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfContestsByTeam(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamResponse> SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfContestsByTeamAsync(SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest request) {
            return base.Channel.getListOfContestsByTeamAsync(request);
        }
        
        public System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamResponse> getListOfContestsByTeamAsync(int team) {
            SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfContestsByTeamRequest();
            inValue.team = team;
            return ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfContestsByTeamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SVM_Webservice_Client.SVMWebservice.getListOfTeamsResponse SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfTeams(SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest request) {
            return base.Channel.getListOfTeams(request);
        }
        
        public SVM_Webservice_Client.SVMWebservice.TeamDTO[] getListOfTeams() {
            SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest();
            SVM_Webservice_Client.SVMWebservice.getListOfTeamsResponse retVal = ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfTeams(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfTeamsResponse> SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType.getListOfTeamsAsync(SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest request) {
            return base.Channel.getListOfTeamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SVM_Webservice_Client.SVMWebservice.getListOfTeamsResponse> getListOfTeamsAsync() {
            SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest inValue = new SVM_Webservice_Client.SVMWebservice.getListOfTeamsRequest();
            return ((SVM_Webservice_Client.SVMWebservice.ExportContestServicePortType)(this)).getListOfTeamsAsync(inValue);
        }
    }
}
